'use client'

import React, { useState } from 'react'
import { Download, Loader2 } from 'lucide-react'
import JSZip from 'jszip'
import { useAlgoCraftStore } from '@/lib/store'
import {
  EXPORT_MAIN_TS,
  EXPORT_USE_ALGORAND_TS,
  EXPORT_WALLET_CONNECT_TS,
  EXPORT_APP_SHELL_TS,
  EXPORT_USE_CONTRACT_STATE_TS,
  EXPORT_INDEX_CSS,
  EXPORT_VITE_CONFIG,
  EXPORT_VITE_ENV,
} from '@/lib/export-templates'
import { EXPORT_ALGORAND_STATE_TS } from '@/lib/export-algorand-state-string'

export function ExportButton() {
  const { generatedFiles, contractId, arc32Spec } = useAlgoCraftStore()
  const [isExporting, setIsExporting] = useState(false)

  const handleExport = async () => {
    setIsExporting(true)
    try {
      const zip = new JSZip()

      const boilerplateFiles = new Set([
        '/mock-wallet.tsx',
        '/mock-algosdk.ts',
        '/index.tsx',
        '/lib/algorand.ts',
      ])
      for (const [path, content] of Object.entries(generatedFiles)) {
        if (boilerplateFiles.has(path)) continue
        const filePath = path.startsWith('/') ? path.slice(1) : path
        zip.file(`src/${filePath}`, content)
      }

      if (arc32Spec) {
        zip.file('src/contract.arc32.json', JSON.stringify(arc32Spec, null, 2))
      }

      zip.file('src/main.tsx', EXPORT_MAIN_TS)
      zip.file('src/index.css', EXPORT_INDEX_CSS)
      zip.file('src/components/WalletConnect.tsx', EXPORT_WALLET_CONNECT_TS)
      zip.file('src/components/AppShell.tsx', EXPORT_APP_SHELL_TS)
      zip.file('src/lib/algorand-state.ts', EXPORT_ALGORAND_STATE_TS)
      zip.file('src/hooks/useAlgorand.ts', EXPORT_USE_ALGORAND_TS)
      zip.file('src/hooks/useContractState.ts', EXPORT_USE_CONTRACT_STATE_TS)
      zip.file('src/vite-env.d.ts', EXPORT_VITE_ENV)

      zip.file(
        'index.html',
        `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AlgoCraft Generated DApp</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`.trim()
      )

      zip.file('package.json', JSON.stringify({
        name: 'algocraft-generated-dapp',
        private: true,
        version: '0.0.0',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'tsc && vite build',
          preview: 'vite preview',
        },
        dependencies: {
          react: '^18.2.0',
          'react-dom': '^18.2.0',
          algosdk: '^3.5.2',
          '@txnlab/use-wallet-react': '^4.6.0',
          '@txnlab/use-wallet': '^4.6.0',
          'lute-connect': '^1.7.0',
          buffer: '^6.0.3',
        },
        devDependencies: {
          '@types/react': '^18.2.0',
          '@types/react-dom': '^18.2.0',
          '@vitejs/plugin-react': '^4.0.0',
          typescript: '^5.0.0',
          vite: '^4.3.0',
        },
      }, null, 2))

      zip.file('vite.config.ts', EXPORT_VITE_CONFIG)

      zip.file('tsconfig.json', JSON.stringify({
        compilerOptions: {
          target: 'ESNext',
          lib: ['DOM', 'DOM.Iterable', 'ESNext'],
          module: 'ESNext',
          skipLibCheck: true,
          moduleResolution: 'node',
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: 'react-jsx',
          strict: true,
          noUnusedLocals: false,
          noUnusedParameters: false,
          noFallthroughCasesInSwitch: true,
        },
        include: ['src'],
      }, null, 2))

      zip.file(
        'README.md',
        `# AlgoCraft Generated DApp

Generated by [AlgoCraft](https://github.com). Includes **full wallet connect** (Pera, Defly, Exodus, Lute) on Algorand Testnet.

## Quick start

\`\`\`bash
npm install
npm run dev
\`\`\`

Open the URL shown (usually http://localhost:5173). Click **Connect Wallet** in the top bar, then use the dApp.

## What's included

| Path | Purpose |
|------|---------|
| \`src/main.tsx\` | \`WalletProvider\` + \`AppShell\` wrapper |
| \`src/components/WalletConnect.tsx\` | Connect / disconnect / copy address |
| \`src/components/AppShell.tsx\` | Header + wallet banner |
| \`src/hooks/useAlgorand.ts\` | algosdk + \`transactionSigner\` from wallet |
| \`src/hooks/useContract.ts\` | ABI helpers for your contract |
| \`src/contract.arc32.json\` | ARC-32 spec |

## Configuration

- **App ID:** \`${contractId ?? 'see useContract.ts'}\`
- **Algod:** Testnet via Algonode (edit \`src/hooks/useAlgorand.ts\` for mainnet)

## Wallet

Uses [@txnlab/use-wallet-react](https://github.com/TxnLab/use-wallet). Install a supported browser wallet extension or mobile wallet before connecting.
`.trim()
      )

      const content = await zip.generateAsync({ type: 'blob' })
      const url = window.URL.createObjectURL(content)
      const link = document.createElement('a')
      link.href = url
      link.download = `algocraft-dapp-${contractId || 'export'}.zip`
      link.click()
      window.URL.revokeObjectURL(url)
    } catch (err) {
      console.error('Export failed:', err)
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={isExporting || Object.keys(generatedFiles).length === 0}
      className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-nb-gold text-background hover:opacity-90 transition-all text-[11px] font-black uppercase tracking-wider shadow-lg shadow-nb-gold/20 disabled:opacity-50 disabled:grayscale"
    >
      {isExporting ? (
        <Loader2 className="w-3.5 h-3.5 animate-spin" />
      ) : (
        <Download className="w-3.5 h-3.5" />
      )}
      {isExporting ? 'Exporting...' : 'Export & Run'}
    </button>
  )
}
